#!/bin/sh

set -uo pipefail

config=$(cat -)
file=$(echo "$config" | jq -r '."source"')
language=$(echo "$config" | jq -r '."natural_language"')

if [ "$language" = "nl" ]; then
  title="Gerenderd"
  empty="Lege oplossing"
  linter_fail="Linter is gestopt met errors"
  build_fail="Docker build is gefaald"
else
  title="Rendered"
  empty="Empty submission"
  linter_fail="Linter exited with errors"
  build_fail="Docker build failed"
fi

echo '{"command": "start-judgement"}'
echo "{\"command\": \"start-tab\", \"title\": \"$title\"}"

if [ -s "$file" ]; then
  if ! hadolint --format json "$file" | jq '.[] | .column -= 1 | .command = "annotate-code" | .row = .line - 1 | .text = .message | .type = if .level == "style" or .level == "ignore" then "info" else .level end | del(.code, .file, .line, .level, .message)'; then
    echo "{\"command\": \"escalate-status\", \"status\": {\"enum\": \"wrong\", \"human\": \"$linter_fail\"}}"
  fi

  if ! err=$(/kaniko/executor -v error --no-push --no-push-cache -f "$file" 2>&1 > /dev/null); then
    jq --null-input \
      --arg description "$err" \
    '{"command": "append-message", "message": {"format": "callout-danger", "description": $description}}'
    echo "{\"command\": \"escalate-status\", \"status\": {\"enum\": \"wrong\", \"human\": \"$build_fail\"}}"
  fi
else
  echo "{\"command\": \"escalate-status\", \"status\": {\"enum\": \"wrong\", \"human\": \"$empty\"}}"
fi

echo '{"command": "close-tab"}'
echo '{"command": "close-judgement"}'
